### ISSUE TITLE
cannot load such file -- bundler

### ISSUE THREAD

**Issue by lsolesen** [felicianotech/jekyll-vagrant-setup#1]
I am getting this error when trying out you scripts:

```
==> default: /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
==> default: :
==> default: cannot load such file -- bundler
==> default:  (
==> default: LoadError
==> default: )
==> default:    from /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<top (required)>'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `load'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `<main>'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
==> default: /home/vagrant/.rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: jekyll: No such file or directory
==> default: /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
==> default: :
==> default: cannot load such file -- bundler
==> default:  (
==> default: LoadError
==> default: )
==> default:    from /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<top (required)>'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `load'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `<main>'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
==> default:    from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by FelicianoTech** [comment]
Hi @lsolesen, this may be too late for you but I believe this latest commit fixes this issue: https://github.com/felicianotech/jekyll-vagrant-setup/commit/5dbc90cfe8dd4b48a3c9e4793576d87f7c0d3bf2
